---
title: 'test'
date: '2020-10-19'
---

```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
library(brms)
```
## Data
```{r read data}
raw_health <- read_csv("AAsD8pYL_1.csv")
```

```{r select variable}
health <- raw_health %>% select(CASEID, dvagegr, dvsex, dvperinc, dvbmimdf, a9cap, g2cap, g3cap, h2hrs, j3, k4, m17cap, m19) 
health <- health %>% clean_names() %>% 
    rename (case_id = caseid, age_first_diagnosed_with_diabetes = a9cap, sex = dvsex,  
            age = dvagegr, personal_income_12months = dvperinc, BMI = dvbmimdf, 
            height = g2cap, weight = g3cap, sleep_hours = h2hrs, 
            cigarettes_smoke_per_day= j3, average_drink_for_12_months = k4, 
            work_hours_per_week = m17cap, nightshift_frequency = m19)
health <- health %>% 
  rowwise() %>% 
  mutate(age_first_diagnosed_with_diabetes = case_when(
      age_first_diagnosed_with_diabetes== 97 ~ as.numeric(NA),
      age_first_diagnosed_with_diabetes== 99 ~ as.numeric(NA),
      TRUE ~ as.numeric(age_first_diagnosed_with_diabetes)
))
health <- health %>% 
  rowwise() %>% 
  mutate(BMI = case_when(
      BMI== 99.9 ~ as.numeric(NA),
      TRUE ~ as.numeric(BMI)
))
health <- health %>% 
  rowwise() %>% 
  mutate(height = case_when(
      height== 998 ~ as.numeric(NA),
      TRUE ~ as.numeric(height)
))
health <- health %>% 
  rowwise() %>% 
  mutate(weight = case_when(
      weight== 998 ~ as.numeric(NA),
      TRUE ~ as.numeric(weight)
))
health <- health %>% 
  rowwise() %>% 
  mutate(work_hours_per_week = case_when(
      work_hours_per_week== 97 ~ as.numeric(NA),
      work_hours_per_week== 99 ~ as.numeric(NA),
      TRUE ~ as.numeric(work_hours_per_week)
))
health <- health %>% 
  rowwise() %>% 
  mutate(sleep_hours = case_when(
      sleep_hours== 99 ~ as.numeric(NA),
      TRUE ~ as.numeric(sleep_hours)
))
health <- health %>% 
  rowwise() %>% 
  mutate(cigarettes_smoke_per_day = case_when(
      cigarettes_smoke_per_day== 97 ~ as.numeric(NA),
      cigarettes_smoke_per_day== 99 ~ as.numeric(NA),
      TRUE ~ as.numeric(cigarettes_smoke_per_day)
))
health <- health %>% 
  rowwise() %>% 
  mutate(age = case_when(
    age== 1 ~ "15 to 17",
    age== 2 ~ "18 to 19",
    age== 3 ~ "20 to 24",
    age== 4 ~ "25 to 29",
    age== 5 ~ "30 to 34",
    age== 6 ~ "35 to 39",
    age== 7 ~ "40 to 44",
    age== 8 ~ "45 to 49",
    age== 9 ~ "50 to 54",
    age== 10 ~ "55 to 59",
    age== 11 ~ "60 to 64",
    age== 12 ~ "65 to 69",
    age== 13 ~ "70 to 74",
    age== 14 ~ "75 to 79",
    age== 15 ~ "80 to 99",
  )) 
health <- health %>% 
  rowwise() %>% 
  mutate(sex = case_when(
    sex== 1 ~ "Male",
    sex== 2 ~ "Female"
))
health <- health %>% 
  rowwise() %>% 
  mutate(personal_income_12months = case_when(
      personal_income_12months== 1 ~  "No income",
      personal_income_12months== 2 ~  "Less than $5,000",
      personal_income_12months== 3 ~  "$5,000 to 9,999",
      personal_income_12months== 4 ~  "$10,000 to 14,999",
      personal_income_12months== 5 ~  "$15,000 to 19,999",
      personal_income_12months== 6 ~  "$20,000 to 29,999",
      personal_income_12months== 7 ~  "$30,000 to 39,999",
      personal_income_12months== 8 ~  "$40,000 to 59,999",
      personal_income_12months== 9 ~  "$60,000 to 79,999",
      personal_income_12months== 10 ~  "$80,000 or more",
      personal_income_12months== 98 ~  "Do not know",
      personal_income_12months== 99 ~  as.character(NA)
))
health <- health %>% 
  rowwise() %>% 
  mutate(average_drink_for_12_months = case_when(
      average_drink_for_12_months== 1 ~ "Every day",
      average_drink_for_12_months== 2 ~ "4 - 6 times a week",
      average_drink_for_12_months== 3 ~ "2 - 3 times a week",
      average_drink_for_12_months== 4 ~ "Once a week",
      average_drink_for_12_months== 5 ~ "Once or twice a month",
      average_drink_for_12_months== 6 ~ "Less often than once a month",
      average_drink_for_12_months== 0 ~ as.character(NA),
      average_drink_for_12_months== 8 ~ "Do not know",
      average_drink_for_12_months== 9 ~ as.character(NA),
))
health <- health %>% 
  rowwise() %>% 
  mutate(nightshift_frequency = case_when(
      nightshift_frequency== 1 ~ "Regularly",
      nightshift_frequency== 2 ~ "Sometimes",
      nightshift_frequency== 3 ~ "Never",
      nightshift_frequency== 0 ~ as.character(NA),
      nightshift_frequency== 9 ~ as.character(NA),
))
health <- na.omit(health)
health
```